const h2Text = document.getElementById("quest-h2");
const btn = document.getElementById("newQuest");
const questions = [
  "¿Qué es algo que jamás le perdonarías a alguien?",
  "¿Odias a alguien en la vida? ¿Por qué?",
  "¿Qué crees que importa más: el amor o la amistad?",
  "¿Qué opinas sobre la religión?",
  "¿Hay algo de lo que crees que siempre te arrepentirás en la vida?",
  "¿Qué es lo que más te gusta de mí?",
  "¿Qué es lo más loco que hiciste de adolescente?",
  "¿Te gustaría poder ir atrás en el tiempo?",
  "¿Cuál es tu peor hábito?",
  "¿Cómo fue tu primera cita?",
  "¿Cuál es el beso más desastroso que has tenido nunca?",
  "¿Cuál es la mayor mentira que has dicho nunca?",
  "¿Qué es lo primero que cambiarías de ti mismo/a?",
  " Si supieras que vas a morir exactamente dentro de un año, ¿cómo cambiarías tu forma de vivir?",
  "¿Qué motivación mueve tu vida?",
  " ¿Cómo te gustaría ser en un futuro?",
  "¿Te has besado con más de una persona el mismo día?",
  "¿Lo que más te gusta de tu cuerpo?",
  "¿Cuál superpoder tendrías?",
  "¿Harías un trío?",
  "¿Quieres casarte?",
  "¿Comida favorita?",
  " ¿Sueño frustrado?",
  "¿Volverías con alguno de tus ex?",
  "¿Has mandado ‘nudes’?",
  "¿Tendrías una relación abierta?",
  "¿Te harías alguna operación?",
  "¿Eres celoso?",
  "¿Tienes una fobia?",
  "¿Mayor inseguridad?",
  "¿Qué consideras raro en ti?",
  "¿Olor favorito?",
  "¿Qué es lo que más te irrita?",
  "¿Le temes a la muerte?",
  "¿Postre favorito?",
  "¿Comida favorita?",
  "¿Cuál fue tu última mentira?",
  "¿Qué es lo que más te excita?",
  "¿Te arrepientes de algo?",
  "¿Quién es la persona más importante en tu vida?",
  "¿Perdonarías una infidelidad?",
  "¿Trabajo de ensueño?",
  "¿Cuál fue el mejor día de tu vida?",
  "¿Qué harías por amor?",
  "¿Tienes algún secreto que no me hayas contado?",
  "¿Te consideras una persona feliz?",
  "¿Cuál es tu límite en las relaciones íntimas?",
  "¿Has jugado con los sentimientos de alguien alguna vez?",
  "¿Dejarías a tu pareja actual si a cambio ganaras un millón de dólares?",
  "¿En qué aspectos crees que eres mejor que los demás?",
  "¿Cómo fue tu peor experiencia sexual?",
  "¿Cuál es la pregunta incómoda que más detestas que te hagan?",
  "¿Hasta qué edad te gustaría vivir?",
  "¿Qué es lo más asqueroso que te ha pasado?",
  " ¿Crees que hay áreas de conocimiento que jamás serías capaz de aprender?",
  " ¿Te han rechazado un beso alguna vez?",
  " ¿Si volvieses a nacer, repetirás tu vida de la misma manera?",
  "Si solo pudieras comer un alimento por el resto de tu vida, ¿cuál sería?",
  " ¿Qué es lo que más te molesta de mí?",
  " ¿Qué cosa quisiste aprender pero nunca lo lograste?",
  "Cuál es la creencia religiosa que consideras más absurda a pesar de estar muy extendida?",
  "¿Cuál es la vez que más tiempo has estado sin ducharte?",
  " ¿Cuál es la comida que más te ha disgustado probar?",
  "¿Qué es lo que más te gustaría tener en la vida y aún no tienes?",
  "¿Te han roto el corazón alguna vez?",
  "¿Cómo fue tu primera experiencia sexual?",
  " ¿Has sufrido algún coma etílico?",
  "¿Crees en los extraterrestres?",
];
let numRandom=Math.round(Math.random() * questions.length)
h2Text.innerText = questions[numRandom]
btn.addEventListener('click', () => {
    location.reload()
})


